### ISSUE TITLE
AWS SDK 1.9.6 version: US-EAST-2 Region not available and giving error when upgraded to 1.1.X

### ISSUE THREAD

**Issue by UmeshKGupta-CDAC** [awslabs/amazon-sqs-java-messaging-lib#52]
Hi all,

 **I have the requirement to set up the SNS(Region: us-east-2) on my project. For this purpose first, I have upgraded the SDK version to 1.11.63. But existing Sqs start giving the below errors.**

Problem: 
**1. Region US-EAST-2 support is not in SDK 1.9.6, so need to upgrade.
2. If upgraded to SDK 1.11.X, then getting below Errors:**

Error:1
java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQSClient.beforeClientExecution(Lcom/amazonaws/AmazonWebServiceRequest;)Lcom/amazonaws/AmazonWebServiceRequest

Error:2 
import com.amazonaws.util.json.JSONObject: missing in this SDK version and lots of code written on this in my app on JSONObject class.

Please, can anyone suggest me the fix for the issue without requiring many changes in my code?
