### ISSUE TITLE
This library no more compatible with latest aws sdk

### ISSUE THREAD

**Issue by kamoor** [awslabs/amazon-sqs-java-messaging-lib#18]
This library works fine with aws sdk 1.9.6 but stopped working after upgrade 1.10.x or later. 

Error:
java.lang.NoSuchMethodError: com.amazonaws.AmazonWebServiceRequest.copyPrivateRequestParameters()Ljava/util/Map;
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2278)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:516)
	at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.getQueueUrl(AmazonSQSMessagingClientWrapper.java:260)
	at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.getQueueUrl(AmazonSQSMessagingClientWrapper.java:230)
	at com.amazon.sqs.javamessaging.SQSSession.createQueue(SQSSession.java:576)

**Comment by navinvishy** [comment]
I think this might be because you have some version mixup. i.e. you still have some 1.9.x being used. Possibly cloudwatch. This thread:
https://github.com/awslabs/amazon-kinesis-client/issues/28
although its for Kinesis, I think its pretty similar.

**Comment by kamoor** [comment]
Yes, I found the mix up. amazon-sqs-messaging-lib is depend on older aws-java-sdk-sqs (1.9.6). I put an exclusion on this to make it work. 
   ```
<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>amazon-sqs-java-messaging-lib</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-sqs</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
I am wondering why this project is not upgrading dependencies?
@navinvishy Thank you very much for your help.

**Comment by eitansela** [comment]
I followed this approach when I got:

> java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQS.deleteMessage(Lcom/amazonaws/services/sqs/model/DeleteMessageRequest;)V

And it didn't help.
I am wondering why this project is not upgrading dependencies?
