### ISSUE TITLE
java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQS.deleteMessage when working with higher than 1.9.6 aws-java-sdk-sqs

### ISSUE THREAD

**Issue by eitansela** [awslabs/amazon-sqs-java-messaging-lib#22]
Hello,

This issues is referenced at: https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/18 but the suggested solution there, don't solve the problem I am facing.

It seems there is a problem with acknowledge and SQSSession.UNORDERED_ACKNOWLEDGE.

I was running the SyncMessageReceiverUnorderedAcknowledge.java program, exactly as written on: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/jmsclient.html#jmsclient-ackmode

When the below code is reached: 

// Acknowledge the message if asked
if (acknowledge) message.acknowledge();

I get the following exception:

Exception in thread "main" **java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQS.deleteMessage(Lcom/amazonaws/services/sqs/model/DeleteMessageRequest;)V**
at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.deleteMessage(AmazonSQSMessagingClientWrapper.java:127)
at com.amazon.sqs.javamessaging.acknowledge.UnorderedAcknowledger.acknowledge(UnorderedAcknowledger.java:42)
at com.amazon.sqs.javamessaging.message.SQSMessage.acknowledge(SQSMessage.java:883)
at sample.sqs.SyncMessageReceiverUnorderedAcknowledge.receiveMessage(SyncMessageReceiverUnorderedAcknowledge.java:116)
at sample.sqs.SyncMessageReceiverUnorderedAcknowledge.main(SyncMessageReceiverUnorderedAcknowledge.java:67)

I am running with the following gradle dependencies:
compile("com.amazonaws:aws-java-sdk-sqs:1.11.13")
compile("com.amazonaws:amazon-sqs-java-messaging-lib:1.0.0") 

I debugged the code, and all the aws amazon java classes looks perfect.

In addition, I created a new program that will run isolated deleteMessage.
With deleteMessage(DeleteMessageRequest deleteMessageRequest) - I get the same exception.
With DeleteMessageBatchResult deleteMessageBatch(DeleteMessageBatchRequest deleteMessageBatchRequest) - It works!

I changed gradle dependencies:
compile("com.amazonaws:aws-java-sdk-sqs:1.9.6")

**And now it works perfect.**

Opening pom.xml of this project, I can see:
  `<properties>
    <aws-java-sdk.version>1.9.6</aws-java-sdk.version>
  </properties>`

When do you plan to change it to the latest one (e.g. 1.11.13)? or one of the latest?

**Comment by bademux** [comment]
lib doesn't work with SQS sdk 1.11.15

**Comment by bademux** [comment]
imho it's better to make aws-java-sdk-sqs provided

**Comment by mlbiam** [comment]
Having the same issue with any of the 1.11.X version, any update on this issue?

**Comment by joshuadavis** [comment]
This looks exactly like what I'm talking about [here](https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/24#issuecomment-234601482)

**Comment by bademux** [comment]
looks like issue was fixed 
https://github.com/awslabs/amazon-sqs-java-messaging-lib/commit/50b4886003d029e61fed110d885ca28b812c6ad1

**Comment by lustosatorres** [comment]
I'm having the same issues when working with SQS operations. The newest version of aws-java-sdk that is working fine for my application is 1.9.10
but with this version some classes deployed in the most recent updates are not available
for example:
com.amazonaws.services.identitymanagement.model.CreatePolicyResult
com.amazonaws.services.identitymanagement.model.CreatePolicyRequest
com.amazonaws.services.simpleemail.AbstractAmazonSimpleEmailService
etc...

**Comment by kuba-aws** [comment]
Fixed in the 1.0.1 release.

**Comment by mmaceachran** [comment]
This error is back for sqs 1.11.123  and message lib 1.0.2

**Comment by kuba-aws** [comment]
I cannot reproduce this issue with a clean project and dependency on the 1.0.2 library. Please double check the AWS SDK version that is being pulled in with your dependencies. Please share a sample that can reproduce this issue.

**Comment by williamdelvalle** [comment]
I have this error in sqs 1.11.865:
`java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQS.deleteMessage(Lcom/amazonaws/services/sqs/model/DeleteMessageRequest;)V`

**Comment by pascalheraud** [comment]
This error is triggered because Amazon changed signature of this method. Your code expect a Void Method (notice the V at the end) but now it returns DeleteMessageResult.
You have to recompile the binary compiled with an older aws SDK.
